#!/usr/bin/env bash
# script that will display information about subdomains.

# Function to display information about a subdomain
function audit_subdomain {
  local domain=$1
  local subdomain=$2
  local record_type
  record_type=$(dig +short $subdomain.$domain | awk '{print $1}')
  local destination
  destination=$(dig +short $subdomain.$domain | awk '{print $2}')
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Get domain and subdomain arguments
domain=$1
subdomain=$2

# If subdomain is not provided, audit default subdomains
if [ -z "$subdomain" ]; then
  audit_subdomain $domain www
  audit_subdomain $domain lb-01
  audit_subdomain $domain web-01
  audit_subdomain $domain web-02
else
  audit_subdomain $domain $subdomain
fi
