#!/usr/bin/env bash
# installs nginx on server

# update package list
sudo apt-get update
# install nginx
sudo apt-get install nginx -y 

# configure Nginx to listen on port 80 and serve custom index.html
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 "Hello World!";
    }
}
EOF'

# Create the custom index.html file
# sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

sudo service nginx restart
