#!/usr/bin/env bash
# congifures your Nginx server to have a custom 404 page that 
# contains the string Ceci n'est pas une page

# Install nginx if it is not already installed
if ! command -v nginx &> /dev/null
then
    apt-get update
    apt-get install -y nginx
fi
# Allow incoming traffic on port 80 (HTTP)
ufw allow 'Nginx HTTP'

# Append "Hello World!" to the default Nginx index.html file
echo "Hello World!" > /var/www/html/index.html

# Create the custom 404 error page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Configure Nginx to use the custom 404 error page
CONFIG_FILE="/etc/nginx/sites-available/default"
if ! grep -q "error_page 404 /404.html;" $CONFIG_FILE; then
    sed -i 's/listen \[::\]:80 default_server;/&\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}/' $CONFIG_FILE
fi
# Restart Nginx to apply the changes
service nginx restart
