#!/usr/bin/env bash
# configure web-02 to be identical to web-01, add a custom HTTP header

# Install nginx if it is not already installed
apt-get update
apt-get install -y nginx

# allow incoming HTTP traffic on port 80
ufw allow 'Nginx HTTP'
# write the string "Hello World!" to the file
echo "Hello World!" >> /var/www/html/index.html
# Use sed to replace the default server block with a new server block that includes a redirect rule for /redirect_me
sed -i '/listen \[::\]:80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}' /etc/nginx/sites-available/default
# Create the custom 404 error page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
# Configure Nginx to use the custom 404 error page
CONFIG_FILE="/etc/nginx/sites-available/default"
sed -i 's/listen \[::\]:80 default_server;/&\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}/' $CONFIG_FILE
# Add custom HTTP response header
# sed -i "/^server {/a \\tadd_header X-Served-By $host;" /etc/nginx/sites-available/default
sudo sed -i "/^server {/a \\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
