#!/usr/bin/env bash
# configure web-02 to be identical to web-01 and
# add a custom HTTP header

# Install Nginx
apt-get update
apt-get install -y nginx

# Add custom HTTP response header
sed -i '/^server {/a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
systemctl restart nginx
