#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

# Install HAproxy
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update -y
apt-get install -y haproxy

# Modify configuration file
sudo cat <<EOF > /etc/haproxy/haproxy.cfg
listen http-in
bind *:80
default_backend servers
mode http
balance roundrobin
server 252133-web-01 34.232.68.72:80 check
server 252133-web-02 52.90.13.69:80 check
EOF

# Enable HAproxy init script
if ! grep -q "ENABLED=1" /etc/default/haproxy; then
    sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
fi
# Restart HAproxy
sudo systemctl restart haproxy
