#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and:
# displays 4 and then bad luck from China for the 4th iteration
# displays 9 and then bad luck from Japan for the 9th iteration
# displays 17 and then bad luck from Italy for the 17th iteration

i=1

while [ $i -le 100 ]
do
    if (( $i % 15 == 0 ))
    then
        echo "FizzBuzz"
    elif (( $i % 3 == 0 ))
    then
        echo "Fizz"
    elif (( $i % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++ ))
done

