#!/usr/bin/env bash
# gives you information about the school file.
# script should check if the file exists and print:
# if the file exists: school file exists
# if the file does not exist: school file does not exist
# If the file exists, print:
# if the file is empty: school file is empty
# if the file is not empty: school file is not empty
# if the file is a regular file: school is a regular file
# if the file is not a regular file: (nothing)

file="school"
if [ -e $file ]
then
    echo "school file exists"
    if [ -s $file ]
    then
        echo "School file is not empty"
    else
        echo "School file is empty"
    fi

    if [ -f $file ]
    then
        echo "School is a regular file"
    fi
else
    echo "school file does not exist"
fi

