#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts_new
echo "127.0.0.2	localhost" > ~/hosts_new
echo "8.8.8.8		facebook.com" >> ~/hosts_new
cp -f ~/hosts_new /etc/hosts
