#!/usr/bin/env bash
# configure a container to run Nginx as the "nginx" user,
# listening on port 8080.

service apache2 stop 2&> /dev/null
pkill apache2

# Set the file permissions of the nginx configuration file to read
# and write for the owner, and read-only for everyone else.
chmod 644 /etc/nginx/nginx.conf

# Change the owner of the nginx configuration file to the nginx user.
chown -R nginx /etc/nginx/nginx.conf

# Replace all occurrences of "80" with "8080" in the default
# nginx configuration file.
su - nginx -c "sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default"

# Restart the nginx service as the nginx user, and redirect any error
# messages to /dev/null.
su - nginx -c "service nginx restart" 2&> /dev/null
